import { NextResponse } from "next/server";
import { createClient as createSupabase } from "@supabase/supabase-js";
import { resolveAdminUserId, logAudit } from "@/lib/audit";

function db() {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) return null;
  return createSupabase(url, key, { auth: { autoRefreshToken: false, persistSession: false } });
}

interface Body {
  status: "SENT" | "OPENED";
}

// Admin-side attribution only (§98) — the deep link itself is generated by
// the storefront at order creation; this just records that an admin followed
// up on a WhatsApp order manually.
export async function PATCH(req: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const client = db();
  if (!client) {
    return NextResponse.json({ error: { message: "Database belum terhubung." } }, { status: 501 });
  }

  const body = (await req.json()) as Body;
  if (body.status !== "SENT" && body.status !== "OPENED") {
    return NextResponse.json({ error: { message: "Status tidak valid." } }, { status: 400 });
  }

  const fields: Record<string, unknown> = { status: body.status };
  if (body.status === "SENT") fields.sent_at = new Date().toISOString();
  if (body.status === "OPENED") fields.opened_at = new Date().toISOString();

  const { error } = await client.from("whatsapp_orders").update(fields).eq("id", id);
  if (error) {
    return NextResponse.json({ error: { message: error.message } }, { status: 500 });
  }

  const adminUserId = await resolveAdminUserId(client);
  await logAudit(client, {
    adminUserId,
    action: "WHATSAPP_ORDER_STATUS_CHANGED",
    entityType: "whatsapp_order",
    entityId: id,
    newValue: fields,
  });

  return NextResponse.json({ ok: true });
}
